# Generated by Django 5.0.2 on 2024-02-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.IntegerField()),
                ('second_number', models.IntegerField()),
                ('add', models.CharField(max_length=50)),
                ('substract', models.CharField(max_length=50)),
                ('multiply', models.CharField(max_length=50)),
                ('devide', models.CharField(max_length=50)),
            ],
        ),
    ]
